- hooks/useApproval.ts
- pages/_app.tsx
- pages/mintKamon/index.tsx
- utils/contractAddress.ts
- To approve before minting with henkaku 
rinkeby contract: 
https://github.com/henkaku-center/podcast-nft/pull/55
staging
https://henkaku-membership-git-add-en-95524e-henkaku-community-dev-team.vercel.app/mintKamon
> feat: Add approval function and utils related to contract

- hooks/useMintWithHenkaku.ts
> add handle BoughtMemberShipNFT event

- components/layouts/layout.tsx
- components/metaMaskAlert/SwitchNetworkAlert.tsx
- pages/index.tsx
- To notify user when they are in different network
desktop | smartphone |
------- | ----------- |
> feat: Add switch network alert

- hooks/useApproval.ts
- hooks/useMintWithHenkaku.ts
- To refactor useApproval hooks
- To fix error when we have different network
> Fix runtime error

- components/footer/index.tsx
- components/layouts/layout.tsx
- package.json
- yarn.lock
> feat: Add footer

- components/layouts/layout.tsx
- components/metaMaskAlert/MetaMaskLeadBanner.tsx
- components/metaMaskAlert/SwitchNetworkAlert.tsx
- components/mintKamon/GenerateImageForm.tsx
- hooks/useApproval.ts
- hooks/useBalanceOf.ts
- hooks/useMintWithHenkaku.ts
- hooks/useTotalSupply.ts
- pages/index.tsx
- pages/mintKamon/index.tsx
- refactoring hooks
- fix typo
> refactoring hooks

- components/mintKamon/GenerateImageForm.tsx
- pages/index.tsx
- pages/mintKamon/index.tsx
> fix tokenURI

- hooks/useApproval.ts
- hooks/useBalanceOf.ts
- hooks/useTokenURI.ts
- pages/index.tsx
fix #47
- Fixed errors when connecting
- Display most recent mint image
notice: 
When unconnected, the contract cannot be connected and the default image is displayed. Since we are employing lazy connect this time, the default image will be displayed in many cases.
> Display most recent mint image

- components/mintKamon/GenerateImageForm.tsx
- components/mintKamon/PreviewNFTImage.tsx
- components/mintKamon/generateImageFormHelper.tsx
- components/mintKamon/index.tsx
- package.json
- pages/mintKamon/index.tsx
- yarn.lock
- To show preview image
- To refactor
> feat: Add preview image

- pages/mintKamon/index.tsx
- to fix a bug which shows broken previewImage when user don't connect to wallet
> fix: Bug which shows broken previewImage when user not connected t

- components/mintKamon/GenerateImageForm.tsx
- contract側はmintしたとき0point、フロントで100を設定していることでチェーンとipfsの情報がずれる
> When minted, point is 0

- components/layouts/layout.tsx
- components/layouts/theme.ts
- components/mintKamon/ApproveForKamon.tsx
- components/mintKamon/GenerateImageForm.tsx
- pages/index.tsx
- pages/mintKamon/index.tsx
- pages/quests/index.tsx
> style: Dark mode

- pages/quests/index.tsx
- Listener is a pain in the ass to think about whether it's uppercase or lower case.
> Enfore Uppercase

- hooks/useApproval.ts
- hooks/useBalanceOf.ts
- hooks/useTokenURI.ts
- hooks/useTotalSupply.ts
- pages/_app.tsx
- pages/index.tsx
- pages/mintKamon/index.tsx
- to fix enable true issue
- modify index page
> feat: Introudce default RPC provier and fix another issue

- components/footer/index.tsx
- components/layouts/layout.tsx
- components/metaMask/Approve.tsx
- components/metaMask/MetaMaskLeadBanner.tsx
- components/metaMask/SwitchNetworkAlert.tsx
- components/mintKamon/ApproveForKamon.tsx
- components/mintKamon/GenerateImageForm.tsx
- components/mintKamon/PreviewNFTImage.tsx
- next-i18next.config.js
- next.config.js
- package.json
- pages/_app.tsx
- pages/index.tsx
- pages/mintKamon/index.tsx
- pages/quests/index.tsx
- public/locales/en/common.json
- public/locales/ja/common.json
- yarn.lock
Closes #28
- Setting up next-i18next
- Front page localized
> Internationalization with next-i18next

- hooks/claim/useClaim.ts
- hooks/quest/useKeywordSubmit.ts
- hooks/useGetError.ts
- utils/handleError.ts
* Fixed a bug that caused all toast errors to be unknown.
> Fix error message

- pages/quests/index.tsx
- public/locales/en/common.json
- public/locales/ja/common.json
fix #82 
nft holder
nft non-holder
> Add condition of NFT possession

- components/metaMask/Approve.tsx
- hooks/badge/useBalanceOf.ts
- hooks/badge/useMintBadge.ts
- locales/en/badge.json
- locales/ja/badge.json
- pages/badges/[id].tsx
> feat: Enable to approve & mint

- components/badges/BadgeBox.tsx
- components/layouts/layout.tsx
- hooks/badge/useBadges.ts
- hooks/badge/useTotalSupply.ts
- i18n.json
- pages/badges/[id].tsx
- pages/badges/index.tsx
- utils/bigNumber.ts
Should I disable the menu link since it is still under development?
Maybe I should have also returned the TokenId from the contract...
> feat: badges page

- components/layouts/layout.tsx
- i18n.json
- locales/en/claim.json
- locales/en/common.json
- locales/ja/claim.json
- locales/ja/common.json
- pages/claim/index.tsx
Closes #75
Was: #76
- Localize claim page
- Localize Claim link on nav bar
- Bonus: localize commented out Badges link
- Bonus fix: dash length had become different between languages
> Localize claim page

- hooks/claim/useClaim.ts
- hooks/quest/useKeywordSubmit.ts
- locales/en/common.json
- locales/ja/common.json
Closes #77
- Localized toasts from keyword hook
- Localized toasts from claim hook
> Localize toasts on hooks

- components/layouts/layout.tsx
- locales/en/common.json
- locales/en/koukan.json
- locales/ja/common.json
- locales/ja/koukan.json
- pages/koukan/index.tsx
> Update koukan UI
